### PR TITLE
Add missing file extension to LICENCE

### PR DESCRIPTION
**Pull request by lukas-vlcek**
### Description
The missing file extension causes the LICENSE file to be missing
in final plugin package distribution.
 
### Issues Resolved
Missing LICENSE file in plugin package.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Thanks! Is it automatically included in the package or explicitly referenced somewhere There's a link to this file in README that would need to be fixed.

**Comment by lukas-vlcek** [comment]
@dblock It is explicitly [referenced](https://github.com/opensearch-project/opensearch-plugin-template-java/blob/24ceac8fa20fe66b2e66dbce4a8c3aa75b6da61b/build.gradle#L28) in the gradle `opensearchplugin` plugin.

For example when you do `./gradlew build` then LICENSE file is missing in `build/testclusters/integTest-0/distro/1.2.3-INTEG_TEST/plugins/rename/` folder.

I updated reference in README file as well.

**Comment by dblock** [comment]
> @dblock It is explicitly [referenced](https://github.com/opensearch-project/opensearch-plugin-template-java/blob/24ceac8fa20fe66b2e66dbce4a8c3aa75b6da61b/build.gradle#L28) in the gradle `opensearchplugin` plugin.
> 
> The LICENSE file is then missing in `build/distributions/rename.zip`. Which means that when you do `./gradlew build` then LICENSE file is missing in `build/testclusters/integTest-0/distro/1.2.3-INTEG_TEST/plugins/rename/` folder.

should CI be failing when this happens?

**Review by dblock — APPROVED** [review]

**Comment by AmiStrn** [comment]
> should CI be failing when this happens?

I will open a separate issue for that covering all the files. 
Good catch  @lukas-vlcek !

**Review by AmiStrn — APPROVED** [review]
LGTM

**Pull request merged**
