### PR TITLE
Update to OpenSearch 1.2.4

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update to OpenSearch 1.2.4 (SNAPSHOT) (which includes https://github.com/opensearch-project/OpenSearch/issues/1814)
 
### Issues Resolved
N/A
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock @AmiStrn removing the workaround since we've fixed the plugin itself

**Review by AmiStrn — APPROVED** [review]
😃 looks good. Thanks @reta !

**Comment by AmiStrn** [comment]
Only worry i have is that this is not backwards compatible with previous versions. But not a big concern really since this has a documented workaround in the previous commit. @dblock wdyt?

**Comment by reta** [comment]
> Only worry i have is that this is not backwards compatible with previous versions. But not a big concern really since this has a documented workaround in the previous commit. @dblock wdyt?
> 
> (Basically leading to the question of managing versions in this repo...)

Thanks @AmiStrn , yeah the workaround would work even with the new versions (with the fix available), won't break anything,  it is just not necessary anymore

**Review by dblock — APPROVED** [review]

**Pull request merged**
