### PR TITLE
remove manual DCO check (done by org-level check)

### LINKED ISSUE #61: [PROPOSAL] Delete the manual DCO check
### What are you proposing?
currently, this repository is using the GH action workflow `dco.yml` to verify that a sign-off is provided. nowadays, this can be controlled directly via GitHub settings (see [the GH documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)).
for OpenSearch this has already been changed a year ago by @VachaShah in https://github.com/opensearch-project/OpenSearch/pull/2317

if this is done it should also be documented that the same needs to be done on repositories started off of this template (presuming they want the DCO).

### What users have asked for this feature?
n/a

### What problems are you trying to solve?
align repositories, use standard features of GitHub.

### What is the developer experience going to be?
n/a

#### Are there any security considerations? 
n/a

#### Are there any breaking changes to the API
n/a

### What is the user experience going to be?
n/a

#### Are there breaking changes to the User Experience?
n/a

### Why should it be built? Any reason not to?
n/a

### What will it take to execute?
* admin user to set the setting on the GH repo
* PR to remove the DCO workflow

### Any remaining open questions?
n/a

### PR DESCRIPTION
**Pull request by rursprung**
the DCO check is activated directly on GitHub in the org-level settings for `opensearch-project` (see the [GitHub documentation]). there's no need for the duplicate check implemented in the workflow anymore.

other projects which are created based on the template which want a DCO check can also just enable this in their settings.

fixes #61

[GitHub documentation]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rursprung** [comment]
note that an admin will have to manually remove the DCO workflow from the list of required GitHub workflows for PRs in the repo settings.

**Comment by rursprung** [comment]
the backport workflow failure seems to be a false-reject:
> Error: Error: For security reasons, this action should only run on merged PRs.

i guess either the workflow is mis-configured or otherwise has a bug since it shouldn't even be running at this moment?

**Comment by reta** [comment]
> i guess either the workflow is mis-configured or otherwise has a bug since it shouldn't even be running at this moment?

Yeah, there are diffs sadly in the way it works on different repos

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@rursprung could you please send manual backport to `2.x` if needed? thank you

**Comment by rursprung** [comment]
> @rursprung could you please send manual backport to `2.x` if needed? thank you

done (#93)

**Pull request merged**
