### PR TITLE
Update Gradle to 8.0.2

### PR DESCRIPTION
**Pull request by reta**
### Description
Update Gradle to 8.0.2

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@AmiStrn  @dblock  could you folks take a look  please?

**Review by AmiStrn — APPROVED** [review]
Thanks @reta !

**Comment by reta** [comment]
@dblock please need your review

**Comment by reta** [comment]
@dblock please need your review

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Sneaked in windows support ;)

**Pull request merged**
