### PR TITLE
Update OpenSearch version to 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update OpenSearch version to 3.0.0-SNAPSHOT

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-plugin-template-java/issues/34

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@prudhvigodithi @lukas-vlcek I was updating some plugins and run into this issue with `publishPluginZipPublicationToMavenLocal` vs `publishToMavenLocal`:

```
$ ./gradlew publishPluginZipPublicationToMavenLocal
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Linux 5.15.0-46-generic (amd64)
  JDK Version           : 11 (Ubuntu JDK)
  JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
  Random Testing Seed   : BA8C165879D2B58D
  In FIPS 140 mode      : false
=======================================

BUILD SUCCESSFUL in 636ms

```

But:

```
$ ./gradlew publishToMavenLocal
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Linux 5.15.0-46-generic (amd64)
  JDK Version           : 11 (Ubuntu JDK)
  JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
  Random Testing Seed   : 4766275014592FF
  In FIPS 140 mode      : false
=======================================
> Task :generatePomFileForPluginZipPublication
Execution optimizations have been disabled for task ':generatePomFileForPluginZipPublication' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/andriy.redko/Workspaces/OpenSearch-plugins/opensearch-plugin-template-java/build/distributions/rename-unspecified.pom'. Reason: Task ':publishNebulaPublicationToMavenLocal' uses this output of task ':generatePomFileForPluginZipPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :publishPluginZipPublicationToMavenLocal
Execution optimizations have been disabled for task ':publishPluginZipPublicationToMavenLocal' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/andriy.redko/Workspaces/OpenSearch-plugins/opensearch-plugin-template-java/build/distributions/rename-unspecified.pom'. Reason: Task ':publishPluginZipPublicationToMavenLocal' uses this output of task ':generatePomFileForNebulaPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 770ms
14 actionable tasks: 5 executed, 9 up-to-date

```

So I decided to create this draft pull request for us to come up with the fix

**Comment by prudhvigodithi** [comment]
Hey @reta thanks for the PR,  just curious this did we see with the updated version of gradle?, I assume we saw this this error at beginning when we onboarded the pluginZip plugin and was fixed in this PR https://github.com/opensearch-project/OpenSearch/pull/3189.

**Comment by reta** [comment]
Hey @prudhvigodithi 

> Hey @reta thanks for the PR, just curious this did we see with the updated version of gradle?

It happens with 7.4.2 as well

> , I assume we saw this this error at beginning when we onboarded the pluginZip plugin and was fixed in this PR [opensearch-project/OpenSearch#3189](https://github.com/opensearch-project/OpenSearch/pull/3189).

We fixed that for `publishPluginZipPublicationToMavenLocal` but never tried with `publishToMavenLocal` ...

**Review by dblock — APPROVED** [review]

**Comment by lukas-vlcek** [comment]
BTW, I added a test case to call `publishToLocalMaven` task in this PR: https://github.com/opensearch-project/OpenSearch/pull/4360
(It is the test called `publishToMavenLocal()` and relevant `publishToMavenLocal.gradle` gradle script.)

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
@reta what is else is pending here?

**Comment by reta** [comment]
> @reta what is else is pending here?

@saratvemulapalli sorry, got a bit sidetracked but these two warnings are better of to be fixed, I will look at them shortly:

```
> Task :generatePomFileForPluginZipPublication
Execution optimizations have been disabled for task ':generatePomFileForPluginZipPublication' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/opensearch-plugin-template-java/build/distributions/rename-unspecified.pom'. Reason: Task ':publishNebulaPublicationToMavenLocal' uses this output of task ':generatePomFileForPluginZipPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :publishPluginZipPublicationToMavenLocal
Execution optimizations have been disabled for task ':publishPluginZipPublicationToMavenLocal' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/opensearch-plugin-template-java/build/distributions/rename-unspecified.pom'. Reason: Task ':publishPluginZipPublicationToMavenLocal' uses this output of task ':generatePomFileForNebulaPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

```

**Comment by saratvemulapalli** [comment]
Thanks @reta !!

**Pull request merged**
