### PR TITLE
Add support for reproducible builds

### PR DESCRIPTION
**Pull request by inglor**
### Description
As per gradle [docs] add support to remove timestamps and package with same order which is required from [reproducible] builds

[docs]: https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
[reproducible]: https://reproducible-builds.org/

### Issues Resolved
As per the suggestion in the `opensearch-project/anomaly-detection` PR [579](https://github.com/opensearch-project/anomaly-detection/pull/579#issuecomment-1258078995)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Since we are here, is there a change we can make in https://github.com/opensearch-project/OpenSearch Gradle plugin plugin to avoid having to put this in every plugin implementation?

**Comment by inglor** [comment]
> Since we are here, is there a change we can make in https://github.com/opensearch-project/OpenSearch Gradle plugin plugin to avoid having to put this in every plugin implementation?

The main project already has it in the main build.gradle and is inherited in the plugins/build.gradle. Is that what you refer to?

**Comment by dblock** [comment]
> > Since we are here, is there a change we can make in https://github.com/opensearch-project/OpenSearch Gradle plugin plugin to avoid having to put this in every plugin implementation?
> 
> The main project already has it in the main build.gradle and is inherited in the plugins/build.gradle. Is that what you refer to?

This PR (into a plugin) adds it in build.gradle. I am looking for a way to enable it in the main project in a way that we don't have to make this PR.

**Comment by inglor** [comment]
> This PR (into a plugin) adds `preserveFileTimestamps` and `reproducibleFileOrder` into the plugin's build.gradle. I am looking for a way to enable it in the main project in a way that we don't have to make this PR and automatically apply to all plugins. The code in the plugin's build.gradle does `apply plugin: 'opensearch.opensearchplugin'`, can it also inherit `preserveFileTimestamps` and `reproducibleFileOrder` automatically?

OK from what I understand there are 3 (4 with optional) places were we can the reproducible fixes

1. The main [OpenSearch project](https://github.com/opensearch-project/OpenSearch), already added [here](https://github.com/opensearch-project/OpenSearch/blob/main/build.gradle#L321-L326)
2. The plugins included with [OpenSearch project](https://github.com/opensearch-project/OpenSearch), inherited already from the above as well.
3. The individual project plugins from OpenSearch like [Anomaly Detection](https://github.com/opensearch-project/anomaly-detection). For these I think we need to do them one by one.
4. [Optional] Add the reproducibility (made up word) to the template for plugins which is this project here.

For number 3 I think you are saying there's another way to do it but I don't know where would that be. Please point me to the right direction and I'm happy to give it a go.

**Comment by dblock** [comment]
@inglor precisely I believe that plugins can inherit these options by including `apply plugin: 'opensearch.opensearchplugin'`. @prudhvigodithi do you know where to do this?

**Comment by prudhvigodithi** [comment]
Hey @inglor @dblock  just acknowledging that I have seen your comment, I will provide you with some details shortly ;)
Thank you

**Comment by prudhvigodithi** [comment]
Hey @inglor so there are some common custom gradle plugins that is being used by all OpenSearch plugins, so all the common logic need not be re-written inside all OpenSearch plugins gradle code.

Example 1: [opensearch.opensearchplugin](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy)
This plugin is applied to all OpenSearch plugins [anomaly-detection](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L97), [job-scheduler ](https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L31) ....

Example 2: [opensearch.pluginzip](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java)
[anomaly-detection](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L102), [job-scheduler ](https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L34) ....

So the ask is if its possible to add the reproducible build logic into one of these custom gradle plugins, so that it need not be added manually to each and every plugin (like done for AD https://github.com/opensearch-project/anomaly-detection/pull/579)

**Comment by prudhvigodithi** [comment]
Something like modifying `AbstractArchiveTask ` properties `PreserveFileTimestamps` and `ReproducibleFileOrder` via those custom gradle plugins added [above](https://github.com/opensearch-project/opensearch-plugin-template-java/pull/38#issuecomment-1264690748) 
Useful Ref: https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java#L87-L88

**Comment by inglor** [comment]
@prudhvigodithi I guess something as simple as this could work:
```
diff --git a/buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy b/buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
--- a/buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy	(revision 4b08d386e7e567071365029bd1d71b3bb0388cc7)
+++ b/buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy	(date 1664745672458)
@@ -29,13 +29,13 @@
 package org.opensearch.gradle.plugin
 
 import com.github.jengelman.gradle.plugins.shadow.ShadowPlugin
+import org.gradle.api.tasks.bundling.AbstractArchiveTask
 import org.opensearch.gradle.BuildPlugin
 import org.opensearch.gradle.NoticeTask
 import org.opensearch.gradle.Version
 import org.opensearch.gradle.VersionProperties
 import org.opensearch.gradle.dependencies.CompileOnlyResolvePlugin
 import org.opensearch.gradle.info.BuildParams
-import org.opensearch.gradle.plugin.PluginPropertiesExtension
 import org.opensearch.gradle.test.RestTestBasePlugin
 import org.opensearch.gradle.testclusters.RunTask
 import org.opensearch.gradle.util.Util
@@ -138,6 +138,12 @@
         project.tasks.register('run', RunTask) {
             dependsOn(project.tasks.bundlePlugin)
         }
+        project.tasks.withType(AbstractArchiveTask.class).configureEach { task ->
+            // ignore file timestamps
+            // be consistent in archive file order
+            task.preserveFileTimestamps = false
+            task.reproducibleFileOrder = true
+        }
     }
 
     private void configurePublishing(Project project, PluginPropertiesExtension extension) {
```

**Comment by AmiStrn** [comment]
@inglor so are we proceeding with this branch or do you want me to close it?

**Comment by inglor** [comment]
@AmiStrn opened a PR for the OpenSearch gradle plugin. Just to confirm my understanding, once that one is merged then from the _next_ release and after any plugin is going to be using that, right? I'm just not sure when the gradle plugin is published to maven repo so it can be used from other projects.

**Comment by prudhvigodithi** [comment]
> @AmiStrn opened a PR for the OpenSearch gradle plugin. Just to confirm my understanding, once that one is merged then from the _next_ release and after any plugin is going to be using that, right? I'm just not sure when the gradle plugin is published to maven repo so it can be used from other projects.

If I may hop in :) 
So all the custom gradle plugins would be part of [build-tools](https://repo1.maven.org/maven2/org/opensearch/gradle/build-tools/), example https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L22, so once this dependency is build, which is done by the [build-workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/build_workflow) when building [OpenSearch component](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.4.0/opensearch-2.4.0.yml#L11-L16), this build-tools would be published to the maven repo, from then whenever a plugin is applied new changes should be picked, this setup can even be tested on local as well where the build-tools would be picked up from local maven repo. @AmiStrn @dblock Please add if i'm missing anything.
Thank you

**Comment by dblock** [comment]
> > @AmiStrn opened a PR for the OpenSearch gradle plugin. Just to confirm my understanding, once that one is merged then from the _next_ release and after any plugin is going to be using that, right? I'm just not sure when the gradle plugin is published to maven repo so it can be used from other projects.
> 
> If I may hop in :) So all the custom gradle plugins would be part of [build-tools](https://repo1.maven.org/maven2/org/opensearch/gradle/build-tools/), example [job-scheduler](https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L22), so once this dependency is build, which is done by the [build-workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/build_workflow) when building [OpenSearch component](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.4.0/opensearch-2.4.0.yml#L11-L16), this build-tools would be published to the maven repo, from then whenever a plugin is applied new changes should be picked, this setup can even be tested on local as well where the build-tools would be picked up from local maven repo. @AmiStrn @dblock Please add if i'm missing anything. Thank you

Yes, that's what I was after. So this PR will no longer be necessary. @inglor Let's confirm when that works and close this without merging?

**Comment by inglor** [comment]
Covered by https://github.com/opensearch-project/OpenSearch/pull/4746

**Pull request closed without merging**
